// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: trace.proto

package tracepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InsightTraceService_GetCurrentMetrics_FullMethodName      = "/insight.trace.v1.InsightTraceService/GetCurrentMetrics"
	InsightTraceService_GetSignature_FullMethodName           = "/insight.trace.v1.InsightTraceService/GetSignature"
	InsightTraceService_GetTrace_FullMethodName               = "/insight.trace.v1.InsightTraceService/GetTrace"
	InsightTraceService_GetStageHistory_FullMethodName        = "/insight.trace.v1.InsightTraceService/GetStageHistory"
	InsightTraceService_StreamMetrics_FullMethodName          = "/insight.trace.v1.InsightTraceService/StreamMetrics"
	InsightTraceService_StreamStageTransitions_FullMethodName = "/insight.trace.v1.InsightTraceService/StreamStageTransitions"
	InsightTraceService_HealthCheck_FullMethodName            = "/insight.trace.v1.InsightTraceService/HealthCheck"
)

// InsightTraceServiceClient is the client API for InsightTraceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InsightTraceServiceClient interface {
	// 현재 메트릭 조회
	GetCurrentMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
	// 워크로드 시그니처 조회
	GetSignature(ctx context.Context, in *GetSignatureRequest, opts ...grpc.CallOption) (*SignatureResponse, error)
	// 전체 트레이스 조회
	GetTrace(ctx context.Context, in *GetTraceRequest, opts ...grpc.CallOption) (*TraceResponse, error)
	// 파이프라인 단계 히스토리 조회
	GetStageHistory(ctx context.Context, in *GetStageHistoryRequest, opts ...grpc.CallOption) (*StageHistoryResponse, error)
	// 메트릭 스트림 (실시간 구독)
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsResponse], error)
	// 단계 전환 이벤트 스트림
	StreamStageTransitions(ctx context.Context, in *StreamStageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StageTransitionEvent], error)
	// 헬스 체크
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type insightTraceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInsightTraceServiceClient(cc grpc.ClientConnInterface) InsightTraceServiceClient {
	return &insightTraceServiceClient{cc}
}

func (c *insightTraceServiceClient) GetCurrentMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, InsightTraceService_GetCurrentMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightTraceServiceClient) GetSignature(ctx context.Context, in *GetSignatureRequest, opts ...grpc.CallOption) (*SignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignatureResponse)
	err := c.cc.Invoke(ctx, InsightTraceService_GetSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightTraceServiceClient) GetTrace(ctx context.Context, in *GetTraceRequest, opts ...grpc.CallOption) (*TraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceResponse)
	err := c.cc.Invoke(ctx, InsightTraceService_GetTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightTraceServiceClient) GetStageHistory(ctx context.Context, in *GetStageHistoryRequest, opts ...grpc.CallOption) (*StageHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StageHistoryResponse)
	err := c.cc.Invoke(ctx, InsightTraceService_GetStageHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightTraceServiceClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InsightTraceService_ServiceDesc.Streams[0], InsightTraceService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, MetricsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsightTraceService_StreamMetricsClient = grpc.ServerStreamingClient[MetricsResponse]

func (c *insightTraceServiceClient) StreamStageTransitions(ctx context.Context, in *StreamStageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StageTransitionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InsightTraceService_ServiceDesc.Streams[1], InsightTraceService_StreamStageTransitions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamStageRequest, StageTransitionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsightTraceService_StreamStageTransitionsClient = grpc.ServerStreamingClient[StageTransitionEvent]

func (c *insightTraceServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, InsightTraceService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsightTraceServiceServer is the server API for InsightTraceService service.
// All implementations must embed UnimplementedInsightTraceServiceServer
// for forward compatibility.
type InsightTraceServiceServer interface {
	// 현재 메트릭 조회
	GetCurrentMetrics(context.Context, *GetMetricsRequest) (*MetricsResponse, error)
	// 워크로드 시그니처 조회
	GetSignature(context.Context, *GetSignatureRequest) (*SignatureResponse, error)
	// 전체 트레이스 조회
	GetTrace(context.Context, *GetTraceRequest) (*TraceResponse, error)
	// 파이프라인 단계 히스토리 조회
	GetStageHistory(context.Context, *GetStageHistoryRequest) (*StageHistoryResponse, error)
	// 메트릭 스트림 (실시간 구독)
	StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[MetricsResponse]) error
	// 단계 전환 이벤트 스트림
	StreamStageTransitions(*StreamStageRequest, grpc.ServerStreamingServer[StageTransitionEvent]) error
	// 헬스 체크
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedInsightTraceServiceServer()
}

// UnimplementedInsightTraceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInsightTraceServiceServer struct{}

func (UnimplementedInsightTraceServiceServer) GetCurrentMetrics(context.Context, *GetMetricsRequest) (*MetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentMetrics not implemented")
}
func (UnimplementedInsightTraceServiceServer) GetSignature(context.Context, *GetSignatureRequest) (*SignatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSignature not implemented")
}
func (UnimplementedInsightTraceServiceServer) GetTrace(context.Context, *GetTraceRequest) (*TraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrace not implemented")
}
func (UnimplementedInsightTraceServiceServer) GetStageHistory(context.Context, *GetStageHistoryRequest) (*StageHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStageHistory not implemented")
}
func (UnimplementedInsightTraceServiceServer) StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[MetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedInsightTraceServiceServer) StreamStageTransitions(*StreamStageRequest, grpc.ServerStreamingServer[StageTransitionEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamStageTransitions not implemented")
}
func (UnimplementedInsightTraceServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedInsightTraceServiceServer) mustEmbedUnimplementedInsightTraceServiceServer() {}
func (UnimplementedInsightTraceServiceServer) testEmbeddedByValue()                             {}

// UnsafeInsightTraceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InsightTraceServiceServer will
// result in compilation errors.
type UnsafeInsightTraceServiceServer interface {
	mustEmbedUnimplementedInsightTraceServiceServer()
}

func RegisterInsightTraceServiceServer(s grpc.ServiceRegistrar, srv InsightTraceServiceServer) {
	// If the following call panics, it indicates UnimplementedInsightTraceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InsightTraceService_ServiceDesc, srv)
}

func _InsightTraceService_GetCurrentMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightTraceServiceServer).GetCurrentMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightTraceService_GetCurrentMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightTraceServiceServer).GetCurrentMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightTraceService_GetSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightTraceServiceServer).GetSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightTraceService_GetSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightTraceServiceServer).GetSignature(ctx, req.(*GetSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightTraceService_GetTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightTraceServiceServer).GetTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightTraceService_GetTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightTraceServiceServer).GetTrace(ctx, req.(*GetTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightTraceService_GetStageHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStageHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightTraceServiceServer).GetStageHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightTraceService_GetStageHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightTraceServiceServer).GetStageHistory(ctx, req.(*GetStageHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightTraceService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InsightTraceServiceServer).StreamMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, MetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsightTraceService_StreamMetricsServer = grpc.ServerStreamingServer[MetricsResponse]

func _InsightTraceService_StreamStageTransitions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamStageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InsightTraceServiceServer).StreamStageTransitions(m, &grpc.GenericServerStream[StreamStageRequest, StageTransitionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsightTraceService_StreamStageTransitionsServer = grpc.ServerStreamingServer[StageTransitionEvent]

func _InsightTraceService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightTraceServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightTraceService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightTraceServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InsightTraceService_ServiceDesc is the grpc.ServiceDesc for InsightTraceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InsightTraceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insight.trace.v1.InsightTraceService",
	HandlerType: (*InsightTraceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentMetrics",
			Handler:    _InsightTraceService_GetCurrentMetrics_Handler,
		},
		{
			MethodName: "GetSignature",
			Handler:    _InsightTraceService_GetSignature_Handler,
		},
		{
			MethodName: "GetTrace",
			Handler:    _InsightTraceService_GetTrace_Handler,
		},
		{
			MethodName: "GetStageHistory",
			Handler:    _InsightTraceService_GetStageHistory_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _InsightTraceService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _InsightTraceService_StreamMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamStageTransitions",
			Handler:       _InsightTraceService_StreamStageTransitions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trace.proto",
}
