// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: trace.proto

package tracepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkloadType int32

const (
	WorkloadType_WORKLOAD_TYPE_UNKNOWN    WorkloadType = 0
	WorkloadType_WORKLOAD_TYPE_IMAGE      WorkloadType = 1
	WorkloadType_WORKLOAD_TYPE_TEXT       WorkloadType = 2
	WorkloadType_WORKLOAD_TYPE_AUDIO      WorkloadType = 3
	WorkloadType_WORKLOAD_TYPE_MULTIMODAL WorkloadType = 4
	WorkloadType_WORKLOAD_TYPE_TABULAR    WorkloadType = 5
)

// Enum value maps for WorkloadType.
var (
	WorkloadType_name = map[int32]string{
		0: "WORKLOAD_TYPE_UNKNOWN",
		1: "WORKLOAD_TYPE_IMAGE",
		2: "WORKLOAD_TYPE_TEXT",
		3: "WORKLOAD_TYPE_AUDIO",
		4: "WORKLOAD_TYPE_MULTIMODAL",
		5: "WORKLOAD_TYPE_TABULAR",
	}
	WorkloadType_value = map[string]int32{
		"WORKLOAD_TYPE_UNKNOWN":    0,
		"WORKLOAD_TYPE_IMAGE":      1,
		"WORKLOAD_TYPE_TEXT":       2,
		"WORKLOAD_TYPE_AUDIO":      3,
		"WORKLOAD_TYPE_MULTIMODAL": 4,
		"WORKLOAD_TYPE_TABULAR":    5,
	}
)

func (x WorkloadType) Enum() *WorkloadType {
	p := new(WorkloadType)
	*p = x
	return p
}

func (x WorkloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_trace_proto_enumTypes[0].Descriptor()
}

func (WorkloadType) Type() protoreflect.EnumType {
	return &file_trace_proto_enumTypes[0]
}

func (x WorkloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadType.Descriptor instead.
func (WorkloadType) EnumDescriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{0}
}

type PipelineStage int32

const (
	PipelineStage_PIPELINE_STAGE_UNKNOWN       PipelineStage = 0
	PipelineStage_PIPELINE_STAGE_PREPROCESSING PipelineStage = 1
	PipelineStage_PIPELINE_STAGE_TRAINING      PipelineStage = 2
	PipelineStage_PIPELINE_STAGE_EVALUATION    PipelineStage = 3
	PipelineStage_PIPELINE_STAGE_SERVING       PipelineStage = 4
)

// Enum value maps for PipelineStage.
var (
	PipelineStage_name = map[int32]string{
		0: "PIPELINE_STAGE_UNKNOWN",
		1: "PIPELINE_STAGE_PREPROCESSING",
		2: "PIPELINE_STAGE_TRAINING",
		3: "PIPELINE_STAGE_EVALUATION",
		4: "PIPELINE_STAGE_SERVING",
	}
	PipelineStage_value = map[string]int32{
		"PIPELINE_STAGE_UNKNOWN":       0,
		"PIPELINE_STAGE_PREPROCESSING": 1,
		"PIPELINE_STAGE_TRAINING":      2,
		"PIPELINE_STAGE_EVALUATION":    3,
		"PIPELINE_STAGE_SERVING":       4,
	}
)

func (x PipelineStage) Enum() *PipelineStage {
	p := new(PipelineStage)
	*p = x
	return p
}

func (x PipelineStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineStage) Descriptor() protoreflect.EnumDescriptor {
	return file_trace_proto_enumTypes[1].Descriptor()
}

func (PipelineStage) Type() protoreflect.EnumType {
	return &file_trace_proto_enumTypes[1]
}

func (x PipelineStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineStage.Descriptor instead.
func (PipelineStage) EnumDescriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{1}
}

type IOPattern int32

const (
	IOPattern_IO_PATTERN_BALANCED        IOPattern = 0
	IOPattern_IO_PATTERN_SEQUENTIAL_READ IOPattern = 1
	IOPattern_IO_PATTERN_RANDOM_READ     IOPattern = 2
	IOPattern_IO_PATTERN_BURST_WRITE     IOPattern = 3
	IOPattern_IO_PATTERN_WRITE_HEAVY     IOPattern = 4
	IOPattern_IO_PATTERN_DISTRIBUTED     IOPattern = 5
)

// Enum value maps for IOPattern.
var (
	IOPattern_name = map[int32]string{
		0: "IO_PATTERN_BALANCED",
		1: "IO_PATTERN_SEQUENTIAL_READ",
		2: "IO_PATTERN_RANDOM_READ",
		3: "IO_PATTERN_BURST_WRITE",
		4: "IO_PATTERN_WRITE_HEAVY",
		5: "IO_PATTERN_DISTRIBUTED",
	}
	IOPattern_value = map[string]int32{
		"IO_PATTERN_BALANCED":        0,
		"IO_PATTERN_SEQUENTIAL_READ": 1,
		"IO_PATTERN_RANDOM_READ":     2,
		"IO_PATTERN_BURST_WRITE":     3,
		"IO_PATTERN_WRITE_HEAVY":     4,
		"IO_PATTERN_DISTRIBUTED":     5,
	}
)

func (x IOPattern) Enum() *IOPattern {
	p := new(IOPattern)
	*p = x
	return p
}

func (x IOPattern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IOPattern) Descriptor() protoreflect.EnumDescriptor {
	return file_trace_proto_enumTypes[2].Descriptor()
}

func (IOPattern) Type() protoreflect.EnumType {
	return &file_trace_proto_enumTypes[2]
}

func (x IOPattern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IOPattern.Descriptor instead.
func (IOPattern) EnumDescriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{2}
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_trace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{0}
}

type GetSignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignatureRequest) Reset() {
	*x = GetSignatureRequest{}
	mi := &file_trace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignatureRequest) ProtoMessage() {}

func (x *GetSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignatureRequest.ProtoReflect.Descriptor instead.
func (*GetSignatureRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{1}
}

type GetTraceRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IncludeMetricsHistory bool                   `protobuf:"varint,1,opt,name=include_metrics_history,json=includeMetricsHistory,proto3" json:"include_metrics_history,omitempty"` // 메트릭 히스토리 포함 여부
	MaxHistoryCount       int32                  `protobuf:"varint,2,opt,name=max_history_count,json=maxHistoryCount,proto3" json:"max_history_count,omitempty"`                   // 최대 히스토리 수
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetTraceRequest) Reset() {
	*x = GetTraceRequest{}
	mi := &file_trace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceRequest) ProtoMessage() {}

func (x *GetTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceRequest.ProtoReflect.Descriptor instead.
func (*GetTraceRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{2}
}

func (x *GetTraceRequest) GetIncludeMetricsHistory() bool {
	if x != nil {
		return x.IncludeMetricsHistory
	}
	return false
}

func (x *GetTraceRequest) GetMaxHistoryCount() int32 {
	if x != nil {
		return x.MaxHistoryCount
	}
	return 0
}

type GetStageHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 최대 개수
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStageHistoryRequest) Reset() {
	*x = GetStageHistoryRequest{}
	mi := &file_trace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStageHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStageHistoryRequest) ProtoMessage() {}

func (x *GetStageHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStageHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetStageHistoryRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{3}
}

func (x *GetStageHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type StreamMetricsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntervalSeconds int32                  `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // 스트리밍 간격 (기본: 5초)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamMetricsRequest) Reset() {
	*x = StreamMetricsRequest{}
	mi := &file_trace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsRequest) ProtoMessage() {}

func (x *StreamMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsRequest.ProtoReflect.Descriptor instead.
func (*StreamMetricsRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{4}
}

func (x *StreamMetricsRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

type StreamStageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStageRequest) Reset() {
	*x = StreamStageRequest{}
	mi := &file_trace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStageRequest) ProtoMessage() {}

func (x *StreamStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStageRequest.ProtoReflect.Descriptor instead.
func (*StreamStageRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{5}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_trace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{6}
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *ResourceMetrics       `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_trace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsResponse) GetMetrics() *ResourceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type SignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     *WorkloadSignature     `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureResponse) Reset() {
	*x = SignatureResponse{}
	mi := &file_trace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureResponse) ProtoMessage() {}

func (x *SignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureResponse.ProtoReflect.Descriptor instead.
func (*SignatureResponse) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{8}
}

func (x *SignatureResponse) GetSignature() *WorkloadSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TraceResponse struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	TraceId          string                  `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	PodName          string                  `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace     string                  `protobuf:"bytes,3,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	NodeName         string                  `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	IsActive         bool                    `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CurrentSignature *WorkloadSignature      `protobuf:"bytes,6,opt,name=current_signature,json=currentSignature,proto3" json:"current_signature,omitempty"`
	StageHistory     []*PipelineStageMetrics `protobuf:"bytes,7,rep,name=stage_history,json=stageHistory,proto3" json:"stage_history,omitempty"`
	MetricsHistory   []*ResourceMetrics      `protobuf:"bytes,8,rep,name=metrics_history,json=metricsHistory,proto3" json:"metrics_history,omitempty"`
	StartTimeUnix    int64                   `protobuf:"varint,9,opt,name=start_time_unix,json=startTimeUnix,proto3" json:"start_time_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TraceResponse) Reset() {
	*x = TraceResponse{}
	mi := &file_trace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceResponse) ProtoMessage() {}

func (x *TraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceResponse.ProtoReflect.Descriptor instead.
func (*TraceResponse) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{9}
}

func (x *TraceResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceResponse) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *TraceResponse) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *TraceResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TraceResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *TraceResponse) GetCurrentSignature() *WorkloadSignature {
	if x != nil {
		return x.CurrentSignature
	}
	return nil
}

func (x *TraceResponse) GetStageHistory() []*PipelineStageMetrics {
	if x != nil {
		return x.StageHistory
	}
	return nil
}

func (x *TraceResponse) GetMetricsHistory() []*ResourceMetrics {
	if x != nil {
		return x.MetricsHistory
	}
	return nil
}

func (x *TraceResponse) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

type StageHistoryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CurrentStage  PipelineStage           `protobuf:"varint,1,opt,name=current_stage,json=currentStage,proto3,enum=insight.trace.v1.PipelineStage" json:"current_stage,omitempty"`
	History       []*PipelineStageMetrics `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageHistoryResponse) Reset() {
	*x = StageHistoryResponse{}
	mi := &file_trace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageHistoryResponse) ProtoMessage() {}

func (x *StageHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageHistoryResponse.ProtoReflect.Descriptor instead.
func (*StageHistoryResponse) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{10}
}

func (x *StageHistoryResponse) GetCurrentStage() PipelineStage {
	if x != nil {
		return x.CurrentStage
	}
	return PipelineStage_PIPELINE_STAGE_UNKNOWN
}

func (x *StageHistoryResponse) GetHistory() []*PipelineStageMetrics {
	if x != nil {
		return x.History
	}
	return nil
}

type StageTransitionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,3,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	FromStage     PipelineStage          `protobuf:"varint,4,opt,name=from_stage,json=fromStage,proto3,enum=insight.trace.v1.PipelineStage" json:"from_stage,omitempty"`
	ToStage       PipelineStage          `protobuf:"varint,5,opt,name=to_stage,json=toStage,proto3,enum=insight.trace.v1.PipelineStage" json:"to_stage,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,6,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageTransitionEvent) Reset() {
	*x = StageTransitionEvent{}
	mi := &file_trace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageTransitionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageTransitionEvent) ProtoMessage() {}

func (x *StageTransitionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageTransitionEvent.ProtoReflect.Descriptor instead.
func (*StageTransitionEvent) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{11}
}

func (x *StageTransitionEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *StageTransitionEvent) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *StageTransitionEvent) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *StageTransitionEvent) GetFromStage() PipelineStage {
	if x != nil {
		return x.FromStage
	}
	return PipelineStage_PIPELINE_STAGE_UNKNOWN
}

func (x *StageTransitionEvent) GetToStage() PipelineStage {
	if x != nil {
		return x.ToStage
	}
	return PipelineStage_PIPELINE_STAGE_UNKNOWN
}

func (x *StageTransitionEvent) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *StageTransitionEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_trace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{12}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type ResourceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnix int64                  `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	// CPU
	CpuUsagePercent      float64 `protobuf:"fixed64,2,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	CpuCores             int32   `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuThrottledPeriodUs int64   `protobuf:"varint,4,opt,name=cpu_throttled_period_us,json=cpuThrottledPeriodUs,proto3" json:"cpu_throttled_period_us,omitempty"`
	// Memory
	MemoryUsageBytes   int64   `protobuf:"varint,5,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	MemoryLimitBytes   int64   `protobuf:"varint,6,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	MemoryUsagePercent float64 `protobuf:"fixed64,7,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	MemoryRssBytes     int64   `protobuf:"varint,8,opt,name=memory_rss_bytes,json=memoryRssBytes,proto3" json:"memory_rss_bytes,omitempty"`
	// GPU
	GpuUsagePercent       float64 `protobuf:"fixed64,9,opt,name=gpu_usage_percent,json=gpuUsagePercent,proto3" json:"gpu_usage_percent,omitempty"`
	GpuMemoryUsedMb       int64   `protobuf:"varint,10,opt,name=gpu_memory_used_mb,json=gpuMemoryUsedMb,proto3" json:"gpu_memory_used_mb,omitempty"`
	GpuMemoryTotalMb      int64   `protobuf:"varint,11,opt,name=gpu_memory_total_mb,json=gpuMemoryTotalMb,proto3" json:"gpu_memory_total_mb,omitempty"`
	GpuTemperatureCelsius float64 `protobuf:"fixed64,12,opt,name=gpu_temperature_celsius,json=gpuTemperatureCelsius,proto3" json:"gpu_temperature_celsius,omitempty"`
	GpuPowerWatts         float64 `protobuf:"fixed64,13,opt,name=gpu_power_watts,json=gpuPowerWatts,proto3" json:"gpu_power_watts,omitempty"`
	// Disk I/O
	DiskReadBytes        int64   `protobuf:"varint,14,opt,name=disk_read_bytes,json=diskReadBytes,proto3" json:"disk_read_bytes,omitempty"`
	DiskWriteBytes       int64   `protobuf:"varint,15,opt,name=disk_write_bytes,json=diskWriteBytes,proto3" json:"disk_write_bytes,omitempty"`
	DiskReadOps          int64   `protobuf:"varint,16,opt,name=disk_read_ops,json=diskReadOps,proto3" json:"disk_read_ops,omitempty"`
	DiskWriteOps         int64   `protobuf:"varint,17,opt,name=disk_write_ops,json=diskWriteOps,proto3" json:"disk_write_ops,omitempty"`
	DiskReadBytesPerSec  float64 `protobuf:"fixed64,18,opt,name=disk_read_bytes_per_sec,json=diskReadBytesPerSec,proto3" json:"disk_read_bytes_per_sec,omitempty"`
	DiskWriteBytesPerSec float64 `protobuf:"fixed64,19,opt,name=disk_write_bytes_per_sec,json=diskWriteBytesPerSec,proto3" json:"disk_write_bytes_per_sec,omitempty"`
	// Network
	NetworkRxBytes       int64   `protobuf:"varint,20,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes       int64   `protobuf:"varint,21,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	NetworkRxBytesPerSec float64 `protobuf:"fixed64,22,opt,name=network_rx_bytes_per_sec,json=networkRxBytesPerSec,proto3" json:"network_rx_bytes_per_sec,omitempty"`
	NetworkTxBytesPerSec float64 `protobuf:"fixed64,23,opt,name=network_tx_bytes_per_sec,json=networkTxBytesPerSec,proto3" json:"network_tx_bytes_per_sec,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceMetrics) Reset() {
	*x = ResourceMetrics{}
	mi := &file_trace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMetrics) ProtoMessage() {}

func (x *ResourceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMetrics.ProtoReflect.Descriptor instead.
func (*ResourceMetrics) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceMetrics) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *ResourceMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ResourceMetrics) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceMetrics) GetCpuThrottledPeriodUs() int64 {
	if x != nil {
		return x.CpuThrottledPeriodUs
	}
	return 0
}

func (x *ResourceMetrics) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *ResourceMetrics) GetMemoryLimitBytes() int64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ResourceMetrics) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *ResourceMetrics) GetMemoryRssBytes() int64 {
	if x != nil {
		return x.MemoryRssBytes
	}
	return 0
}

func (x *ResourceMetrics) GetGpuUsagePercent() float64 {
	if x != nil {
		return x.GpuUsagePercent
	}
	return 0
}

func (x *ResourceMetrics) GetGpuMemoryUsedMb() int64 {
	if x != nil {
		return x.GpuMemoryUsedMb
	}
	return 0
}

func (x *ResourceMetrics) GetGpuMemoryTotalMb() int64 {
	if x != nil {
		return x.GpuMemoryTotalMb
	}
	return 0
}

func (x *ResourceMetrics) GetGpuTemperatureCelsius() float64 {
	if x != nil {
		return x.GpuTemperatureCelsius
	}
	return 0
}

func (x *ResourceMetrics) GetGpuPowerWatts() float64 {
	if x != nil {
		return x.GpuPowerWatts
	}
	return 0
}

func (x *ResourceMetrics) GetDiskReadBytes() int64 {
	if x != nil {
		return x.DiskReadBytes
	}
	return 0
}

func (x *ResourceMetrics) GetDiskWriteBytes() int64 {
	if x != nil {
		return x.DiskWriteBytes
	}
	return 0
}

func (x *ResourceMetrics) GetDiskReadOps() int64 {
	if x != nil {
		return x.DiskReadOps
	}
	return 0
}

func (x *ResourceMetrics) GetDiskWriteOps() int64 {
	if x != nil {
		return x.DiskWriteOps
	}
	return 0
}

func (x *ResourceMetrics) GetDiskReadBytesPerSec() float64 {
	if x != nil {
		return x.DiskReadBytesPerSec
	}
	return 0
}

func (x *ResourceMetrics) GetDiskWriteBytesPerSec() float64 {
	if x != nil {
		return x.DiskWriteBytesPerSec
	}
	return 0
}

func (x *ResourceMetrics) GetNetworkRxBytes() int64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *ResourceMetrics) GetNetworkTxBytes() int64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *ResourceMetrics) GetNetworkRxBytesPerSec() float64 {
	if x != nil {
		return x.NetworkRxBytesPerSec
	}
	return 0
}

func (x *ResourceMetrics) GetNetworkTxBytesPerSec() float64 {
	if x != nil {
		return x.NetworkTxBytesPerSec
	}
	return 0
}

type WorkloadSignature struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PodName            string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace       string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	ContainerName      string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	WorkloadType       WorkloadType           `protobuf:"varint,4,opt,name=workload_type,json=workloadType,proto3,enum=insight.trace.v1.WorkloadType" json:"workload_type,omitempty"`
	CurrentStage       PipelineStage          `protobuf:"varint,5,opt,name=current_stage,json=currentStage,proto3,enum=insight.trace.v1.PipelineStage" json:"current_stage,omitempty"`
	IoPattern          IOPattern              `protobuf:"varint,6,opt,name=io_pattern,json=ioPattern,proto3,enum=insight.trace.v1.IOPattern" json:"io_pattern,omitempty"`
	Confidence         float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	DetectedFramework  string                 `protobuf:"bytes,8,opt,name=detected_framework,json=detectedFramework,proto3" json:"detected_framework,omitempty"`
	DetectedVersion    string                 `protobuf:"bytes,9,opt,name=detected_version,json=detectedVersion,proto3" json:"detected_version,omitempty"`
	IsGpuWorkload      bool                   `protobuf:"varint,10,opt,name=is_gpu_workload,json=isGpuWorkload,proto3" json:"is_gpu_workload,omitempty"`
	IsDistributed      bool                   `protobuf:"varint,11,opt,name=is_distributed,json=isDistributed,proto3" json:"is_distributed,omitempty"`
	EstimatedBatchSize int32                  `protobuf:"varint,12,opt,name=estimated_batch_size,json=estimatedBatchSize,proto3" json:"estimated_batch_size,omitempty"`
	// 스토리지 추천
	RecommendedStorageClass   string `protobuf:"bytes,13,opt,name=recommended_storage_class,json=recommendedStorageClass,proto3" json:"recommended_storage_class,omitempty"`
	RecommendedStorageSize    string `protobuf:"bytes,14,opt,name=recommended_storage_size,json=recommendedStorageSize,proto3" json:"recommended_storage_size,omitempty"`
	RecommendedIops           int64  `protobuf:"varint,15,opt,name=recommended_iops,json=recommendedIops,proto3" json:"recommended_iops,omitempty"`
	RecommendedThroughputMbps int64  `protobuf:"varint,16,opt,name=recommended_throughput_mbps,json=recommendedThroughputMbps,proto3" json:"recommended_throughput_mbps,omitempty"`
	FirstSeenUnix             int64  `protobuf:"varint,17,opt,name=first_seen_unix,json=firstSeenUnix,proto3" json:"first_seen_unix,omitempty"`
	LastSeenUnix              int64  `protobuf:"varint,18,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	UpdatedAtUnix             int64  `protobuf:"varint,19,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *WorkloadSignature) Reset() {
	*x = WorkloadSignature{}
	mi := &file_trace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSignature) ProtoMessage() {}

func (x *WorkloadSignature) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSignature.ProtoReflect.Descriptor instead.
func (*WorkloadSignature) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{14}
}

func (x *WorkloadSignature) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *WorkloadSignature) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *WorkloadSignature) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *WorkloadSignature) GetWorkloadType() WorkloadType {
	if x != nil {
		return x.WorkloadType
	}
	return WorkloadType_WORKLOAD_TYPE_UNKNOWN
}

func (x *WorkloadSignature) GetCurrentStage() PipelineStage {
	if x != nil {
		return x.CurrentStage
	}
	return PipelineStage_PIPELINE_STAGE_UNKNOWN
}

func (x *WorkloadSignature) GetIoPattern() IOPattern {
	if x != nil {
		return x.IoPattern
	}
	return IOPattern_IO_PATTERN_BALANCED
}

func (x *WorkloadSignature) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *WorkloadSignature) GetDetectedFramework() string {
	if x != nil {
		return x.DetectedFramework
	}
	return ""
}

func (x *WorkloadSignature) GetDetectedVersion() string {
	if x != nil {
		return x.DetectedVersion
	}
	return ""
}

func (x *WorkloadSignature) GetIsGpuWorkload() bool {
	if x != nil {
		return x.IsGpuWorkload
	}
	return false
}

func (x *WorkloadSignature) GetIsDistributed() bool {
	if x != nil {
		return x.IsDistributed
	}
	return false
}

func (x *WorkloadSignature) GetEstimatedBatchSize() int32 {
	if x != nil {
		return x.EstimatedBatchSize
	}
	return 0
}

func (x *WorkloadSignature) GetRecommendedStorageClass() string {
	if x != nil {
		return x.RecommendedStorageClass
	}
	return ""
}

func (x *WorkloadSignature) GetRecommendedStorageSize() string {
	if x != nil {
		return x.RecommendedStorageSize
	}
	return ""
}

func (x *WorkloadSignature) GetRecommendedIops() int64 {
	if x != nil {
		return x.RecommendedIops
	}
	return 0
}

func (x *WorkloadSignature) GetRecommendedThroughputMbps() int64 {
	if x != nil {
		return x.RecommendedThroughputMbps
	}
	return 0
}

func (x *WorkloadSignature) GetFirstSeenUnix() int64 {
	if x != nil {
		return x.FirstSeenUnix
	}
	return 0
}

func (x *WorkloadSignature) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *WorkloadSignature) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type PipelineStageMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Stage             PipelineStage          `protobuf:"varint,1,opt,name=stage,proto3,enum=insight.trace.v1.PipelineStage" json:"stage,omitempty"`
	StartTimeUnix     int64                  `protobuf:"varint,2,opt,name=start_time_unix,json=startTimeUnix,proto3" json:"start_time_unix,omitempty"`
	EndTimeUnix       int64                  `protobuf:"varint,3,opt,name=end_time_unix,json=endTimeUnix,proto3" json:"end_time_unix,omitempty"`
	DurationSeconds   float64                `protobuf:"fixed64,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	AvgCpuUsage       float64                `protobuf:"fixed64,5,opt,name=avg_cpu_usage,json=avgCpuUsage,proto3" json:"avg_cpu_usage,omitempty"`
	MaxCpuUsage       float64                `protobuf:"fixed64,6,opt,name=max_cpu_usage,json=maxCpuUsage,proto3" json:"max_cpu_usage,omitempty"`
	AvgMemoryUsage    float64                `protobuf:"fixed64,7,opt,name=avg_memory_usage,json=avgMemoryUsage,proto3" json:"avg_memory_usage,omitempty"`
	MaxMemoryUsage    float64                `protobuf:"fixed64,8,opt,name=max_memory_usage,json=maxMemoryUsage,proto3" json:"max_memory_usage,omitempty"`
	AvgGpuUsage       float64                `protobuf:"fixed64,9,opt,name=avg_gpu_usage,json=avgGpuUsage,proto3" json:"avg_gpu_usage,omitempty"`
	MaxGpuUsage       float64                `protobuf:"fixed64,10,opt,name=max_gpu_usage,json=maxGpuUsage,proto3" json:"max_gpu_usage,omitempty"`
	TotalReadBytes    int64                  `protobuf:"varint,11,opt,name=total_read_bytes,json=totalReadBytes,proto3" json:"total_read_bytes,omitempty"`
	TotalWriteBytes   int64                  `protobuf:"varint,12,opt,name=total_write_bytes,json=totalWriteBytes,proto3" json:"total_write_bytes,omitempty"`
	ReadWriteRatio    float64                `protobuf:"fixed64,13,opt,name=read_write_ratio,json=readWriteRatio,proto3" json:"read_write_ratio,omitempty"`
	DetectedIoPattern IOPattern              `protobuf:"varint,14,opt,name=detected_io_pattern,json=detectedIoPattern,proto3,enum=insight.trace.v1.IOPattern" json:"detected_io_pattern,omitempty"`
	SampleCount       int32                  `protobuf:"varint,15,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PipelineStageMetrics) Reset() {
	*x = PipelineStageMetrics{}
	mi := &file_trace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineStageMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStageMetrics) ProtoMessage() {}

func (x *PipelineStageMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_trace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStageMetrics.ProtoReflect.Descriptor instead.
func (*PipelineStageMetrics) Descriptor() ([]byte, []int) {
	return file_trace_proto_rawDescGZIP(), []int{15}
}

func (x *PipelineStageMetrics) GetStage() PipelineStage {
	if x != nil {
		return x.Stage
	}
	return PipelineStage_PIPELINE_STAGE_UNKNOWN
}

func (x *PipelineStageMetrics) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

func (x *PipelineStageMetrics) GetEndTimeUnix() int64 {
	if x != nil {
		return x.EndTimeUnix
	}
	return 0
}

func (x *PipelineStageMetrics) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *PipelineStageMetrics) GetAvgCpuUsage() float64 {
	if x != nil {
		return x.AvgCpuUsage
	}
	return 0
}

func (x *PipelineStageMetrics) GetMaxCpuUsage() float64 {
	if x != nil {
		return x.MaxCpuUsage
	}
	return 0
}

func (x *PipelineStageMetrics) GetAvgMemoryUsage() float64 {
	if x != nil {
		return x.AvgMemoryUsage
	}
	return 0
}

func (x *PipelineStageMetrics) GetMaxMemoryUsage() float64 {
	if x != nil {
		return x.MaxMemoryUsage
	}
	return 0
}

func (x *PipelineStageMetrics) GetAvgGpuUsage() float64 {
	if x != nil {
		return x.AvgGpuUsage
	}
	return 0
}

func (x *PipelineStageMetrics) GetMaxGpuUsage() float64 {
	if x != nil {
		return x.MaxGpuUsage
	}
	return 0
}

func (x *PipelineStageMetrics) GetTotalReadBytes() int64 {
	if x != nil {
		return x.TotalReadBytes
	}
	return 0
}

func (x *PipelineStageMetrics) GetTotalWriteBytes() int64 {
	if x != nil {
		return x.TotalWriteBytes
	}
	return 0
}

func (x *PipelineStageMetrics) GetReadWriteRatio() float64 {
	if x != nil {
		return x.ReadWriteRatio
	}
	return 0
}

func (x *PipelineStageMetrics) GetDetectedIoPattern() IOPattern {
	if x != nil {
		return x.DetectedIoPattern
	}
	return IOPattern_IO_PATTERN_BALANCED
}

func (x *PipelineStageMetrics) GetSampleCount() int32 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

var File_trace_proto protoreflect.FileDescriptor

const file_trace_proto_rawDesc = "" +
	"\n" +
	"\vtrace.proto\x12\x10insight.trace.v1\"\x13\n" +
	"\x11GetMetricsRequest\"\x15\n" +
	"\x13GetSignatureRequest\"u\n" +
	"\x0fGetTraceRequest\x126\n" +
	"\x17include_metrics_history\x18\x01 \x01(\bR\x15includeMetricsHistory\x12*\n" +
	"\x11max_history_count\x18\x02 \x01(\x05R\x0fmaxHistoryCount\".\n" +
	"\x16GetStageHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"A\n" +
	"\x14StreamMetricsRequest\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\x05R\x0fintervalSeconds\"\x14\n" +
	"\x12StreamStageRequest\"\x14\n" +
	"\x12HealthCheckRequest\"N\n" +
	"\x0fMetricsResponse\x12;\n" +
	"\ametrics\x18\x01 \x01(\v2!.insight.trace.v1.ResourceMetricsR\ametrics\"V\n" +
	"\x11SignatureResponse\x12A\n" +
	"\tsignature\x18\x01 \x01(\v2#.insight.trace.v1.WorkloadSignatureR\tsignature\"\xb7\x03\n" +
	"\rTraceResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x03 \x01(\tR\fpodNamespace\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12P\n" +
	"\x11current_signature\x18\x06 \x01(\v2#.insight.trace.v1.WorkloadSignatureR\x10currentSignature\x12K\n" +
	"\rstage_history\x18\a \x03(\v2&.insight.trace.v1.PipelineStageMetricsR\fstageHistory\x12J\n" +
	"\x0fmetrics_history\x18\b \x03(\v2!.insight.trace.v1.ResourceMetricsR\x0emetricsHistory\x12&\n" +
	"\x0fstart_time_unix\x18\t \x01(\x03R\rstartTimeUnix\"\x9e\x01\n" +
	"\x14StageHistoryResponse\x12D\n" +
	"\rcurrent_stage\x18\x01 \x01(\x0e2\x1f.insight.trace.v1.PipelineStageR\fcurrentStage\x12@\n" +
	"\ahistory\x18\x02 \x03(\v2&.insight.trace.v1.PipelineStageMetricsR\ahistory\"\xac\x02\n" +
	"\x14StageTransitionEvent\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x03 \x01(\tR\fpodNamespace\x12>\n" +
	"\n" +
	"from_stage\x18\x04 \x01(\x0e2\x1f.insight.trace.v1.PipelineStageR\tfromStage\x12:\n" +
	"\bto_stage\x18\x05 \x01(\x0e2\x1f.insight.trace.v1.PipelineStageR\atoStage\x12%\n" +
	"\x0etimestamp_unix\x18\x06 \x01(\x03R\rtimestampUnix\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"t\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\"\xa6\b\n" +
	"\x0fResourceMetrics\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\x12*\n" +
	"\x11cpu_usage_percent\x18\x02 \x01(\x01R\x0fcpuUsagePercent\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x05R\bcpuCores\x125\n" +
	"\x17cpu_throttled_period_us\x18\x04 \x01(\x03R\x14cpuThrottledPeriodUs\x12,\n" +
	"\x12memory_usage_bytes\x18\x05 \x01(\x03R\x10memoryUsageBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x06 \x01(\x03R\x10memoryLimitBytes\x120\n" +
	"\x14memory_usage_percent\x18\a \x01(\x01R\x12memoryUsagePercent\x12(\n" +
	"\x10memory_rss_bytes\x18\b \x01(\x03R\x0ememoryRssBytes\x12*\n" +
	"\x11gpu_usage_percent\x18\t \x01(\x01R\x0fgpuUsagePercent\x12+\n" +
	"\x12gpu_memory_used_mb\x18\n" +
	" \x01(\x03R\x0fgpuMemoryUsedMb\x12-\n" +
	"\x13gpu_memory_total_mb\x18\v \x01(\x03R\x10gpuMemoryTotalMb\x126\n" +
	"\x17gpu_temperature_celsius\x18\f \x01(\x01R\x15gpuTemperatureCelsius\x12&\n" +
	"\x0fgpu_power_watts\x18\r \x01(\x01R\rgpuPowerWatts\x12&\n" +
	"\x0fdisk_read_bytes\x18\x0e \x01(\x03R\rdiskReadBytes\x12(\n" +
	"\x10disk_write_bytes\x18\x0f \x01(\x03R\x0ediskWriteBytes\x12\"\n" +
	"\rdisk_read_ops\x18\x10 \x01(\x03R\vdiskReadOps\x12$\n" +
	"\x0edisk_write_ops\x18\x11 \x01(\x03R\fdiskWriteOps\x124\n" +
	"\x17disk_read_bytes_per_sec\x18\x12 \x01(\x01R\x13diskReadBytesPerSec\x126\n" +
	"\x18disk_write_bytes_per_sec\x18\x13 \x01(\x01R\x14diskWriteBytesPerSec\x12(\n" +
	"\x10network_rx_bytes\x18\x14 \x01(\x03R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\x15 \x01(\x03R\x0enetworkTxBytes\x126\n" +
	"\x18network_rx_bytes_per_sec\x18\x16 \x01(\x01R\x14networkRxBytesPerSec\x126\n" +
	"\x18network_tx_bytes_per_sec\x18\x17 \x01(\x01R\x14networkTxBytesPerSec\"\x93\a\n" +
	"\x11WorkloadSignature\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12C\n" +
	"\rworkload_type\x18\x04 \x01(\x0e2\x1e.insight.trace.v1.WorkloadTypeR\fworkloadType\x12D\n" +
	"\rcurrent_stage\x18\x05 \x01(\x0e2\x1f.insight.trace.v1.PipelineStageR\fcurrentStage\x12:\n" +
	"\n" +
	"io_pattern\x18\x06 \x01(\x0e2\x1b.insight.trace.v1.IOPatternR\tioPattern\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12-\n" +
	"\x12detected_framework\x18\b \x01(\tR\x11detectedFramework\x12)\n" +
	"\x10detected_version\x18\t \x01(\tR\x0fdetectedVersion\x12&\n" +
	"\x0fis_gpu_workload\x18\n" +
	" \x01(\bR\risGpuWorkload\x12%\n" +
	"\x0eis_distributed\x18\v \x01(\bR\risDistributed\x120\n" +
	"\x14estimated_batch_size\x18\f \x01(\x05R\x12estimatedBatchSize\x12:\n" +
	"\x19recommended_storage_class\x18\r \x01(\tR\x17recommendedStorageClass\x128\n" +
	"\x18recommended_storage_size\x18\x0e \x01(\tR\x16recommendedStorageSize\x12)\n" +
	"\x10recommended_iops\x18\x0f \x01(\x03R\x0frecommendedIops\x12>\n" +
	"\x1brecommended_throughput_mbps\x18\x10 \x01(\x03R\x19recommendedThroughputMbps\x12&\n" +
	"\x0ffirst_seen_unix\x18\x11 \x01(\x03R\rfirstSeenUnix\x12$\n" +
	"\x0elast_seen_unix\x18\x12 \x01(\x03R\flastSeenUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x13 \x01(\x03R\rupdatedAtUnix\"\x98\x05\n" +
	"\x14PipelineStageMetrics\x125\n" +
	"\x05stage\x18\x01 \x01(\x0e2\x1f.insight.trace.v1.PipelineStageR\x05stage\x12&\n" +
	"\x0fstart_time_unix\x18\x02 \x01(\x03R\rstartTimeUnix\x12\"\n" +
	"\rend_time_unix\x18\x03 \x01(\x03R\vendTimeUnix\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x01R\x0fdurationSeconds\x12\"\n" +
	"\ravg_cpu_usage\x18\x05 \x01(\x01R\vavgCpuUsage\x12\"\n" +
	"\rmax_cpu_usage\x18\x06 \x01(\x01R\vmaxCpuUsage\x12(\n" +
	"\x10avg_memory_usage\x18\a \x01(\x01R\x0eavgMemoryUsage\x12(\n" +
	"\x10max_memory_usage\x18\b \x01(\x01R\x0emaxMemoryUsage\x12\"\n" +
	"\ravg_gpu_usage\x18\t \x01(\x01R\vavgGpuUsage\x12\"\n" +
	"\rmax_gpu_usage\x18\n" +
	" \x01(\x01R\vmaxGpuUsage\x12(\n" +
	"\x10total_read_bytes\x18\v \x01(\x03R\x0etotalReadBytes\x12*\n" +
	"\x11total_write_bytes\x18\f \x01(\x03R\x0ftotalWriteBytes\x12(\n" +
	"\x10read_write_ratio\x18\r \x01(\x01R\x0ereadWriteRatio\x12K\n" +
	"\x13detected_io_pattern\x18\x0e \x01(\x0e2\x1b.insight.trace.v1.IOPatternR\x11detectedIoPattern\x12!\n" +
	"\fsample_count\x18\x0f \x01(\x05R\vsampleCount*\xac\x01\n" +
	"\fWorkloadType\x12\x19\n" +
	"\x15WORKLOAD_TYPE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13WORKLOAD_TYPE_IMAGE\x10\x01\x12\x16\n" +
	"\x12WORKLOAD_TYPE_TEXT\x10\x02\x12\x17\n" +
	"\x13WORKLOAD_TYPE_AUDIO\x10\x03\x12\x1c\n" +
	"\x18WORKLOAD_TYPE_MULTIMODAL\x10\x04\x12\x19\n" +
	"\x15WORKLOAD_TYPE_TABULAR\x10\x05*\xa5\x01\n" +
	"\rPipelineStage\x12\x1a\n" +
	"\x16PIPELINE_STAGE_UNKNOWN\x10\x00\x12 \n" +
	"\x1cPIPELINE_STAGE_PREPROCESSING\x10\x01\x12\x1b\n" +
	"\x17PIPELINE_STAGE_TRAINING\x10\x02\x12\x1d\n" +
	"\x19PIPELINE_STAGE_EVALUATION\x10\x03\x12\x1a\n" +
	"\x16PIPELINE_STAGE_SERVING\x10\x04*\xb4\x01\n" +
	"\tIOPattern\x12\x17\n" +
	"\x13IO_PATTERN_BALANCED\x10\x00\x12\x1e\n" +
	"\x1aIO_PATTERN_SEQUENTIAL_READ\x10\x01\x12\x1a\n" +
	"\x16IO_PATTERN_RANDOM_READ\x10\x02\x12\x1a\n" +
	"\x16IO_PATTERN_BURST_WRITE\x10\x03\x12\x1a\n" +
	"\x16IO_PATTERN_WRITE_HEAVY\x10\x04\x12\x1a\n" +
	"\x16IO_PATTERN_DISTRIBUTED\x10\x052\xa7\x05\n" +
	"\x13InsightTraceService\x12[\n" +
	"\x11GetCurrentMetrics\x12#.insight.trace.v1.GetMetricsRequest\x1a!.insight.trace.v1.MetricsResponse\x12Z\n" +
	"\fGetSignature\x12%.insight.trace.v1.GetSignatureRequest\x1a#.insight.trace.v1.SignatureResponse\x12N\n" +
	"\bGetTrace\x12!.insight.trace.v1.GetTraceRequest\x1a\x1f.insight.trace.v1.TraceResponse\x12c\n" +
	"\x0fGetStageHistory\x12(.insight.trace.v1.GetStageHistoryRequest\x1a&.insight.trace.v1.StageHistoryResponse\x12\\\n" +
	"\rStreamMetrics\x12&.insight.trace.v1.StreamMetricsRequest\x1a!.insight.trace.v1.MetricsResponse0\x01\x12h\n" +
	"\x16StreamStageTransitions\x12$.insight.trace.v1.StreamStageRequest\x1a&.insight.trace.v1.StageTransitionEvent0\x01\x12Z\n" +
	"\vHealthCheck\x12$.insight.trace.v1.HealthCheckRequest\x1a%.insight.trace.v1.HealthCheckResponseB\x1dZ\x1binsight-trace/proto/tracepbb\x06proto3"

var (
	file_trace_proto_rawDescOnce sync.Once
	file_trace_proto_rawDescData []byte
)

func file_trace_proto_rawDescGZIP() []byte {
	file_trace_proto_rawDescOnce.Do(func() {
		file_trace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trace_proto_rawDesc), len(file_trace_proto_rawDesc)))
	})
	return file_trace_proto_rawDescData
}

var file_trace_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_trace_proto_goTypes = []any{
	(WorkloadType)(0),              // 0: insight.trace.v1.WorkloadType
	(PipelineStage)(0),             // 1: insight.trace.v1.PipelineStage
	(IOPattern)(0),                 // 2: insight.trace.v1.IOPattern
	(*GetMetricsRequest)(nil),      // 3: insight.trace.v1.GetMetricsRequest
	(*GetSignatureRequest)(nil),    // 4: insight.trace.v1.GetSignatureRequest
	(*GetTraceRequest)(nil),        // 5: insight.trace.v1.GetTraceRequest
	(*GetStageHistoryRequest)(nil), // 6: insight.trace.v1.GetStageHistoryRequest
	(*StreamMetricsRequest)(nil),   // 7: insight.trace.v1.StreamMetricsRequest
	(*StreamStageRequest)(nil),     // 8: insight.trace.v1.StreamStageRequest
	(*HealthCheckRequest)(nil),     // 9: insight.trace.v1.HealthCheckRequest
	(*MetricsResponse)(nil),        // 10: insight.trace.v1.MetricsResponse
	(*SignatureResponse)(nil),      // 11: insight.trace.v1.SignatureResponse
	(*TraceResponse)(nil),          // 12: insight.trace.v1.TraceResponse
	(*StageHistoryResponse)(nil),   // 13: insight.trace.v1.StageHistoryResponse
	(*StageTransitionEvent)(nil),   // 14: insight.trace.v1.StageTransitionEvent
	(*HealthCheckResponse)(nil),    // 15: insight.trace.v1.HealthCheckResponse
	(*ResourceMetrics)(nil),        // 16: insight.trace.v1.ResourceMetrics
	(*WorkloadSignature)(nil),      // 17: insight.trace.v1.WorkloadSignature
	(*PipelineStageMetrics)(nil),   // 18: insight.trace.v1.PipelineStageMetrics
}
var file_trace_proto_depIdxs = []int32{
	16, // 0: insight.trace.v1.MetricsResponse.metrics:type_name -> insight.trace.v1.ResourceMetrics
	17, // 1: insight.trace.v1.SignatureResponse.signature:type_name -> insight.trace.v1.WorkloadSignature
	17, // 2: insight.trace.v1.TraceResponse.current_signature:type_name -> insight.trace.v1.WorkloadSignature
	18, // 3: insight.trace.v1.TraceResponse.stage_history:type_name -> insight.trace.v1.PipelineStageMetrics
	16, // 4: insight.trace.v1.TraceResponse.metrics_history:type_name -> insight.trace.v1.ResourceMetrics
	1,  // 5: insight.trace.v1.StageHistoryResponse.current_stage:type_name -> insight.trace.v1.PipelineStage
	18, // 6: insight.trace.v1.StageHistoryResponse.history:type_name -> insight.trace.v1.PipelineStageMetrics
	1,  // 7: insight.trace.v1.StageTransitionEvent.from_stage:type_name -> insight.trace.v1.PipelineStage
	1,  // 8: insight.trace.v1.StageTransitionEvent.to_stage:type_name -> insight.trace.v1.PipelineStage
	0,  // 9: insight.trace.v1.WorkloadSignature.workload_type:type_name -> insight.trace.v1.WorkloadType
	1,  // 10: insight.trace.v1.WorkloadSignature.current_stage:type_name -> insight.trace.v1.PipelineStage
	2,  // 11: insight.trace.v1.WorkloadSignature.io_pattern:type_name -> insight.trace.v1.IOPattern
	1,  // 12: insight.trace.v1.PipelineStageMetrics.stage:type_name -> insight.trace.v1.PipelineStage
	2,  // 13: insight.trace.v1.PipelineStageMetrics.detected_io_pattern:type_name -> insight.trace.v1.IOPattern
	3,  // 14: insight.trace.v1.InsightTraceService.GetCurrentMetrics:input_type -> insight.trace.v1.GetMetricsRequest
	4,  // 15: insight.trace.v1.InsightTraceService.GetSignature:input_type -> insight.trace.v1.GetSignatureRequest
	5,  // 16: insight.trace.v1.InsightTraceService.GetTrace:input_type -> insight.trace.v1.GetTraceRequest
	6,  // 17: insight.trace.v1.InsightTraceService.GetStageHistory:input_type -> insight.trace.v1.GetStageHistoryRequest
	7,  // 18: insight.trace.v1.InsightTraceService.StreamMetrics:input_type -> insight.trace.v1.StreamMetricsRequest
	8,  // 19: insight.trace.v1.InsightTraceService.StreamStageTransitions:input_type -> insight.trace.v1.StreamStageRequest
	9,  // 20: insight.trace.v1.InsightTraceService.HealthCheck:input_type -> insight.trace.v1.HealthCheckRequest
	10, // 21: insight.trace.v1.InsightTraceService.GetCurrentMetrics:output_type -> insight.trace.v1.MetricsResponse
	11, // 22: insight.trace.v1.InsightTraceService.GetSignature:output_type -> insight.trace.v1.SignatureResponse
	12, // 23: insight.trace.v1.InsightTraceService.GetTrace:output_type -> insight.trace.v1.TraceResponse
	13, // 24: insight.trace.v1.InsightTraceService.GetStageHistory:output_type -> insight.trace.v1.StageHistoryResponse
	10, // 25: insight.trace.v1.InsightTraceService.StreamMetrics:output_type -> insight.trace.v1.MetricsResponse
	14, // 26: insight.trace.v1.InsightTraceService.StreamStageTransitions:output_type -> insight.trace.v1.StageTransitionEvent
	15, // 27: insight.trace.v1.InsightTraceService.HealthCheck:output_type -> insight.trace.v1.HealthCheckResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_trace_proto_init() }
func file_trace_proto_init() {
	if File_trace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trace_proto_rawDesc), len(file_trace_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trace_proto_goTypes,
		DependencyIndexes: file_trace_proto_depIdxs,
		EnumInfos:         file_trace_proto_enumTypes,
		MessageInfos:      file_trace_proto_msgTypes,
	}.Build()
	File_trace_proto = out.File
	file_trace_proto_goTypes = nil
	file_trace_proto_depIdxs = nil
}
