// ============================================
// APOLLO - Adaptive Policy Optimization for Low-Latency I/O
// KETI AI Storage System Communication Protocol
// ============================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: apollo.proto

package apollo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InsightService_ReportWorkloadSignature_FullMethodName  = "/apollo.InsightService/ReportWorkloadSignature"
	InsightService_StreamWorkloadSignatures_FullMethodName = "/apollo.InsightService/StreamWorkloadSignatures"
	InsightService_ReportClusterInsight_FullMethodName     = "/apollo.InsightService/ReportClusterInsight"
	InsightService_StreamClusterInsights_FullMethodName    = "/apollo.InsightService/StreamClusterInsights"
)

// InsightServiceClient is the client API for InsightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InsightService: Trace/Scope -> APOLLO 데이터 수집
type InsightServiceClient interface {
	// Insight Trace에서 워크로드 시그니처 전송
	ReportWorkloadSignature(ctx context.Context, in *WorkloadSignature, opts ...grpc.CallOption) (*ReportResponse, error)
	// Insight Trace에서 워크로드 시그니처 스트리밍
	StreamWorkloadSignatures(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WorkloadSignature, StreamResponse], error)
	// Insight Scope에서 클러스터 인사이트 전송
	ReportClusterInsight(ctx context.Context, in *ClusterInsight, opts ...grpc.CallOption) (*ReportResponse, error)
	// Insight Scope에서 클러스터 인사이트 스트리밍
	StreamClusterInsights(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ClusterInsight, StreamResponse], error)
}

type insightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInsightServiceClient(cc grpc.ClientConnInterface) InsightServiceClient {
	return &insightServiceClient{cc}
}

func (c *insightServiceClient) ReportWorkloadSignature(ctx context.Context, in *WorkloadSignature, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, InsightService_ReportWorkloadSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightServiceClient) StreamWorkloadSignatures(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WorkloadSignature, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InsightService_ServiceDesc.Streams[0], InsightService_StreamWorkloadSignatures_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkloadSignature, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsightService_StreamWorkloadSignaturesClient = grpc.ClientStreamingClient[WorkloadSignature, StreamResponse]

func (c *insightServiceClient) ReportClusterInsight(ctx context.Context, in *ClusterInsight, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, InsightService_ReportClusterInsight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightServiceClient) StreamClusterInsights(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ClusterInsight, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InsightService_ServiceDesc.Streams[1], InsightService_StreamClusterInsights_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClusterInsight, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsightService_StreamClusterInsightsClient = grpc.ClientStreamingClient[ClusterInsight, StreamResponse]

// InsightServiceServer is the server API for InsightService service.
// All implementations must embed UnimplementedInsightServiceServer
// for forward compatibility.
//
// InsightService: Trace/Scope -> APOLLO 데이터 수집
type InsightServiceServer interface {
	// Insight Trace에서 워크로드 시그니처 전송
	ReportWorkloadSignature(context.Context, *WorkloadSignature) (*ReportResponse, error)
	// Insight Trace에서 워크로드 시그니처 스트리밍
	StreamWorkloadSignatures(grpc.ClientStreamingServer[WorkloadSignature, StreamResponse]) error
	// Insight Scope에서 클러스터 인사이트 전송
	ReportClusterInsight(context.Context, *ClusterInsight) (*ReportResponse, error)
	// Insight Scope에서 클러스터 인사이트 스트리밍
	StreamClusterInsights(grpc.ClientStreamingServer[ClusterInsight, StreamResponse]) error
	mustEmbedUnimplementedInsightServiceServer()
}

// UnimplementedInsightServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInsightServiceServer struct{}

func (UnimplementedInsightServiceServer) ReportWorkloadSignature(context.Context, *WorkloadSignature) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportWorkloadSignature not implemented")
}
func (UnimplementedInsightServiceServer) StreamWorkloadSignatures(grpc.ClientStreamingServer[WorkloadSignature, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamWorkloadSignatures not implemented")
}
func (UnimplementedInsightServiceServer) ReportClusterInsight(context.Context, *ClusterInsight) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportClusterInsight not implemented")
}
func (UnimplementedInsightServiceServer) StreamClusterInsights(grpc.ClientStreamingServer[ClusterInsight, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamClusterInsights not implemented")
}
func (UnimplementedInsightServiceServer) mustEmbedUnimplementedInsightServiceServer() {}
func (UnimplementedInsightServiceServer) testEmbeddedByValue()                        {}

// UnsafeInsightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InsightServiceServer will
// result in compilation errors.
type UnsafeInsightServiceServer interface {
	mustEmbedUnimplementedInsightServiceServer()
}

func RegisterInsightServiceServer(s grpc.ServiceRegistrar, srv InsightServiceServer) {
	// If the following call panics, it indicates UnimplementedInsightServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InsightService_ServiceDesc, srv)
}

func _InsightService_ReportWorkloadSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkloadSignature)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightServiceServer).ReportWorkloadSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightService_ReportWorkloadSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightServiceServer).ReportWorkloadSignature(ctx, req.(*WorkloadSignature))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightService_StreamWorkloadSignatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InsightServiceServer).StreamWorkloadSignatures(&grpc.GenericServerStream[WorkloadSignature, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsightService_StreamWorkloadSignaturesServer = grpc.ClientStreamingServer[WorkloadSignature, StreamResponse]

func _InsightService_ReportClusterInsight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterInsight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightServiceServer).ReportClusterInsight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightService_ReportClusterInsight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightServiceServer).ReportClusterInsight(ctx, req.(*ClusterInsight))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightService_StreamClusterInsights_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InsightServiceServer).StreamClusterInsights(&grpc.GenericServerStream[ClusterInsight, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsightService_StreamClusterInsightsServer = grpc.ClientStreamingServer[ClusterInsight, StreamResponse]

// InsightService_ServiceDesc is the grpc.ServiceDesc for InsightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InsightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apollo.InsightService",
	HandlerType: (*InsightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportWorkloadSignature",
			Handler:    _InsightService_ReportWorkloadSignature_Handler,
		},
		{
			MethodName: "ReportClusterInsight",
			Handler:    _InsightService_ReportClusterInsight_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWorkloadSignatures",
			Handler:       _InsightService_StreamWorkloadSignatures_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamClusterInsights",
			Handler:       _InsightService_StreamClusterInsights_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "apollo.proto",
}

const (
	SchedulingPolicyService_GetSchedulingPolicy_FullMethodName    = "/apollo.SchedulingPolicyService/GetSchedulingPolicy"
	SchedulingPolicyService_ReportSchedulingResult_FullMethodName = "/apollo.SchedulingPolicyService/ReportSchedulingResult"
)

// SchedulingPolicyServiceClient is the client API for SchedulingPolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SchedulingPolicyService: APOLLO -> Scheduler 정책 전달
type SchedulingPolicyServiceClient interface {
	// 특정 Pod에 대한 스케줄링 정책 요청
	GetSchedulingPolicy(ctx context.Context, in *SchedulingPolicyRequest, opts ...grpc.CallOption) (*SchedulingPolicy, error)
	// 스케줄링 결과 피드백
	ReportSchedulingResult(ctx context.Context, in *SchedulingResult, opts ...grpc.CallOption) (*ReportResponse, error)
}

type schedulingPolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulingPolicyServiceClient(cc grpc.ClientConnInterface) SchedulingPolicyServiceClient {
	return &schedulingPolicyServiceClient{cc}
}

func (c *schedulingPolicyServiceClient) GetSchedulingPolicy(ctx context.Context, in *SchedulingPolicyRequest, opts ...grpc.CallOption) (*SchedulingPolicy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulingPolicy)
	err := c.cc.Invoke(ctx, SchedulingPolicyService_GetSchedulingPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingPolicyServiceClient) ReportSchedulingResult(ctx context.Context, in *SchedulingResult, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, SchedulingPolicyService_ReportSchedulingResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulingPolicyServiceServer is the server API for SchedulingPolicyService service.
// All implementations must embed UnimplementedSchedulingPolicyServiceServer
// for forward compatibility.
//
// SchedulingPolicyService: APOLLO -> Scheduler 정책 전달
type SchedulingPolicyServiceServer interface {
	// 특정 Pod에 대한 스케줄링 정책 요청
	GetSchedulingPolicy(context.Context, *SchedulingPolicyRequest) (*SchedulingPolicy, error)
	// 스케줄링 결과 피드백
	ReportSchedulingResult(context.Context, *SchedulingResult) (*ReportResponse, error)
	mustEmbedUnimplementedSchedulingPolicyServiceServer()
}

// UnimplementedSchedulingPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulingPolicyServiceServer struct{}

func (UnimplementedSchedulingPolicyServiceServer) GetSchedulingPolicy(context.Context, *SchedulingPolicyRequest) (*SchedulingPolicy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchedulingPolicy not implemented")
}
func (UnimplementedSchedulingPolicyServiceServer) ReportSchedulingResult(context.Context, *SchedulingResult) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSchedulingResult not implemented")
}
func (UnimplementedSchedulingPolicyServiceServer) mustEmbedUnimplementedSchedulingPolicyServiceServer() {
}
func (UnimplementedSchedulingPolicyServiceServer) testEmbeddedByValue() {}

// UnsafeSchedulingPolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulingPolicyServiceServer will
// result in compilation errors.
type UnsafeSchedulingPolicyServiceServer interface {
	mustEmbedUnimplementedSchedulingPolicyServiceServer()
}

func RegisterSchedulingPolicyServiceServer(s grpc.ServiceRegistrar, srv SchedulingPolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedSchedulingPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulingPolicyService_ServiceDesc, srv)
}

func _SchedulingPolicyService_GetSchedulingPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulingPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingPolicyServiceServer).GetSchedulingPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingPolicyService_GetSchedulingPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingPolicyServiceServer).GetSchedulingPolicy(ctx, req.(*SchedulingPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingPolicyService_ReportSchedulingResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulingResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingPolicyServiceServer).ReportSchedulingResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingPolicyService_ReportSchedulingResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingPolicyServiceServer).ReportSchedulingResult(ctx, req.(*SchedulingResult))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulingPolicyService_ServiceDesc is the grpc.ServiceDesc for SchedulingPolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulingPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apollo.SchedulingPolicyService",
	HandlerType: (*SchedulingPolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchedulingPolicy",
			Handler:    _SchedulingPolicyService_GetSchedulingPolicy_Handler,
		},
		{
			MethodName: "ReportSchedulingResult",
			Handler:    _SchedulingPolicyService_ReportSchedulingResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apollo.proto",
}

const (
	OrchestrationPolicyService_SubscribePolicies_FullMethodName      = "/apollo.OrchestrationPolicyService/SubscribePolicies"
	OrchestrationPolicyService_GetOrchestrationPolicy_FullMethodName = "/apollo.OrchestrationPolicyService/GetOrchestrationPolicy"
	OrchestrationPolicyService_ReportExecutionResult_FullMethodName  = "/apollo.OrchestrationPolicyService/ReportExecutionResult"
)

// OrchestrationPolicyServiceClient is the client API for OrchestrationPolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrchestrationPolicyService: APOLLO -> Orchestrator 정책 전달
type OrchestrationPolicyServiceClient interface {
	// 오케스트레이션 정책 구독 (스트리밍)
	SubscribePolicies(ctx context.Context, in *PolicySubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrchestrationPolicy], error)
	// 특정 워크로드에 대한 정책 요청
	GetOrchestrationPolicy(ctx context.Context, in *OrchestrationPolicyRequest, opts ...grpc.CallOption) (*OrchestrationPolicy, error)
	// 정책 실행 결과 피드백
	ReportExecutionResult(ctx context.Context, in *ExecutionResult, opts ...grpc.CallOption) (*ReportResponse, error)
}

type orchestrationPolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestrationPolicyServiceClient(cc grpc.ClientConnInterface) OrchestrationPolicyServiceClient {
	return &orchestrationPolicyServiceClient{cc}
}

func (c *orchestrationPolicyServiceClient) SubscribePolicies(ctx context.Context, in *PolicySubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrchestrationPolicy], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestrationPolicyService_ServiceDesc.Streams[0], OrchestrationPolicyService_SubscribePolicies_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PolicySubscription, OrchestrationPolicy]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestrationPolicyService_SubscribePoliciesClient = grpc.ServerStreamingClient[OrchestrationPolicy]

func (c *orchestrationPolicyServiceClient) GetOrchestrationPolicy(ctx context.Context, in *OrchestrationPolicyRequest, opts ...grpc.CallOption) (*OrchestrationPolicy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrchestrationPolicy)
	err := c.cc.Invoke(ctx, OrchestrationPolicyService_GetOrchestrationPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationPolicyServiceClient) ReportExecutionResult(ctx context.Context, in *ExecutionResult, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, OrchestrationPolicyService_ReportExecutionResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestrationPolicyServiceServer is the server API for OrchestrationPolicyService service.
// All implementations must embed UnimplementedOrchestrationPolicyServiceServer
// for forward compatibility.
//
// OrchestrationPolicyService: APOLLO -> Orchestrator 정책 전달
type OrchestrationPolicyServiceServer interface {
	// 오케스트레이션 정책 구독 (스트리밍)
	SubscribePolicies(*PolicySubscription, grpc.ServerStreamingServer[OrchestrationPolicy]) error
	// 특정 워크로드에 대한 정책 요청
	GetOrchestrationPolicy(context.Context, *OrchestrationPolicyRequest) (*OrchestrationPolicy, error)
	// 정책 실행 결과 피드백
	ReportExecutionResult(context.Context, *ExecutionResult) (*ReportResponse, error)
	mustEmbedUnimplementedOrchestrationPolicyServiceServer()
}

// UnimplementedOrchestrationPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestrationPolicyServiceServer struct{}

func (UnimplementedOrchestrationPolicyServiceServer) SubscribePolicies(*PolicySubscription, grpc.ServerStreamingServer[OrchestrationPolicy]) error {
	return status.Error(codes.Unimplemented, "method SubscribePolicies not implemented")
}
func (UnimplementedOrchestrationPolicyServiceServer) GetOrchestrationPolicy(context.Context, *OrchestrationPolicyRequest) (*OrchestrationPolicy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrchestrationPolicy not implemented")
}
func (UnimplementedOrchestrationPolicyServiceServer) ReportExecutionResult(context.Context, *ExecutionResult) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportExecutionResult not implemented")
}
func (UnimplementedOrchestrationPolicyServiceServer) mustEmbedUnimplementedOrchestrationPolicyServiceServer() {
}
func (UnimplementedOrchestrationPolicyServiceServer) testEmbeddedByValue() {}

// UnsafeOrchestrationPolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestrationPolicyServiceServer will
// result in compilation errors.
type UnsafeOrchestrationPolicyServiceServer interface {
	mustEmbedUnimplementedOrchestrationPolicyServiceServer()
}

func RegisterOrchestrationPolicyServiceServer(s grpc.ServiceRegistrar, srv OrchestrationPolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestrationPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestrationPolicyService_ServiceDesc, srv)
}

func _OrchestrationPolicyService_SubscribePolicies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PolicySubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestrationPolicyServiceServer).SubscribePolicies(m, &grpc.GenericServerStream[PolicySubscription, OrchestrationPolicy]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestrationPolicyService_SubscribePoliciesServer = grpc.ServerStreamingServer[OrchestrationPolicy]

func _OrchestrationPolicyService_GetOrchestrationPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrchestrationPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationPolicyServiceServer).GetOrchestrationPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationPolicyService_GetOrchestrationPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationPolicyServiceServer).GetOrchestrationPolicy(ctx, req.(*OrchestrationPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestrationPolicyService_ReportExecutionResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationPolicyServiceServer).ReportExecutionResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationPolicyService_ReportExecutionResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationPolicyServiceServer).ReportExecutionResult(ctx, req.(*ExecutionResult))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestrationPolicyService_ServiceDesc is the grpc.ServiceDesc for OrchestrationPolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestrationPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apollo.OrchestrationPolicyService",
	HandlerType: (*OrchestrationPolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrchestrationPolicy",
			Handler:    _OrchestrationPolicyService_GetOrchestrationPolicy_Handler,
		},
		{
			MethodName: "ReportExecutionResult",
			Handler:    _OrchestrationPolicyService_ReportExecutionResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribePolicies",
			Handler:       _OrchestrationPolicyService_SubscribePolicies_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "apollo.proto",
}

const (
	ForecastService_GetResourcePrediction_FullMethodName = "/apollo.ForecastService/GetResourcePrediction"
	ForecastService_GetClusterPrediction_FullMethodName  = "/apollo.ForecastService/GetClusterPrediction"
)

// ForecastServiceClient is the client API for ForecastService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ForecastService: 내부 예측 서비스
type ForecastServiceClient interface {
	// 특정 노드의 자원 예측 요청
	GetResourcePrediction(ctx context.Context, in *PredictionRequest, opts ...grpc.CallOption) (*ResourcePrediction, error)
	// 클러스터 전체 예측
	GetClusterPrediction(ctx context.Context, in *ClusterPredictionRequest, opts ...grpc.CallOption) (*ClusterPrediction, error)
}

type forecastServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForecastServiceClient(cc grpc.ClientConnInterface) ForecastServiceClient {
	return &forecastServiceClient{cc}
}

func (c *forecastServiceClient) GetResourcePrediction(ctx context.Context, in *PredictionRequest, opts ...grpc.CallOption) (*ResourcePrediction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcePrediction)
	err := c.cc.Invoke(ctx, ForecastService_GetResourcePrediction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastServiceClient) GetClusterPrediction(ctx context.Context, in *ClusterPredictionRequest, opts ...grpc.CallOption) (*ClusterPrediction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterPrediction)
	err := c.cc.Invoke(ctx, ForecastService_GetClusterPrediction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForecastServiceServer is the server API for ForecastService service.
// All implementations must embed UnimplementedForecastServiceServer
// for forward compatibility.
//
// ForecastService: 내부 예측 서비스
type ForecastServiceServer interface {
	// 특정 노드의 자원 예측 요청
	GetResourcePrediction(context.Context, *PredictionRequest) (*ResourcePrediction, error)
	// 클러스터 전체 예측
	GetClusterPrediction(context.Context, *ClusterPredictionRequest) (*ClusterPrediction, error)
	mustEmbedUnimplementedForecastServiceServer()
}

// UnimplementedForecastServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForecastServiceServer struct{}

func (UnimplementedForecastServiceServer) GetResourcePrediction(context.Context, *PredictionRequest) (*ResourcePrediction, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResourcePrediction not implemented")
}
func (UnimplementedForecastServiceServer) GetClusterPrediction(context.Context, *ClusterPredictionRequest) (*ClusterPrediction, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterPrediction not implemented")
}
func (UnimplementedForecastServiceServer) mustEmbedUnimplementedForecastServiceServer() {}
func (UnimplementedForecastServiceServer) testEmbeddedByValue()                         {}

// UnsafeForecastServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForecastServiceServer will
// result in compilation errors.
type UnsafeForecastServiceServer interface {
	mustEmbedUnimplementedForecastServiceServer()
}

func RegisterForecastServiceServer(s grpc.ServiceRegistrar, srv ForecastServiceServer) {
	// If the following call panics, it indicates UnimplementedForecastServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForecastService_ServiceDesc, srv)
}

func _ForecastService_GetResourcePrediction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastServiceServer).GetResourcePrediction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastService_GetResourcePrediction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastServiceServer).GetResourcePrediction(ctx, req.(*PredictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastService_GetClusterPrediction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterPredictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastServiceServer).GetClusterPrediction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastService_GetClusterPrediction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastServiceServer).GetClusterPrediction(ctx, req.(*ClusterPredictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForecastService_ServiceDesc is the grpc.ServiceDesc for ForecastService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForecastService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apollo.ForecastService",
	HandlerType: (*ForecastServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResourcePrediction",
			Handler:    _ForecastService_GetResourcePrediction_Handler,
		},
		{
			MethodName: "GetClusterPrediction",
			Handler:    _ForecastService_GetClusterPrediction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apollo.proto",
}
